services:
  grafana:
    image: grafana/grafana:latest
    container_name: powerconsumption-grafana
    env_file:
      - .env
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped


  influxdb:
    image: influxdb:2.7-alpine
    container_name: powerconsumption-influxdb
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    ports:
      - ${INFLUX_HOST_PORT}:${INFLUX_CONTAINER_PORT}
    restart: unless-stopped

  ingester:
    image: powerconsumption-ingester:6
    build: ./ingester
    container_name: powerconsumption-ingester
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-storage:
  grafana-storage:
